In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from path import Path
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
#file path will be update to the table created in our sql database
file_path = "/Users/joshzaragoza/Arizona_Election_Project/Resources/Voter Data/Leg_District4.csv"
df_voters = pd.read_csv(file_path)
df_voters.head(10)

,PartyName,Sex,Age,Zip,LastName,FirstName,MiddleName,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,85018,Lozano,Javier,Mata,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,85254,Meell,Lana,Kay,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,85260,Collins,Anne,Melissa,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,85016,Bernhisel,Sandra,Jane,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,85018,Blanchard,Richard,Sheldon,Caucasian,6.78,99.31,0.7,16.74,1.73
5,Other,M,61,85018,Sexton,Kirk,Thomas,Caucasian,30.89,90.70,25.1,68.62,16.10
6,Other,F,58,85018,Sexton,Michelle,Lynn,Caucasian,54.23,92.16,30.0,82.50,25.78
7,Other,F,64,85018,Perry,Karen,Louise,Caucasian,15.13,99.34,1.2,42.51,6.80
8,Republican,M,79,85018,Skinner,Raymond,Alister,Caucasian,6.50,98.68,0.6,12.99,5.87
9,Other,M,44,85251,Dwyer,Jason,Paul,Caucasian,70.74,35.36,1.1,19.96,15.50

In [3]:
df_voters.drop(columns=["Zip","LastName","FirstName","MiddleName"], inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
140572,Republican,M,77,NaN,33.95,65.32,9.9,NaN,NaN
140573,Republican,F,57,NaN,18.43,67.75,4.3,NaN,NaN
140574,Republican,F,45,NaN,17.29,70.12,14.8,NaN,NaN
140575,Republican,M,60,NaN,13.54,67.16,4.3,NaN,NaN
140576,Republican,M,38,NaN,16.52,64.36,11.2,NaN,NaN

In [4]:
# Columns
df_voters.count()

PartyName             140577
Sex                   140577
Age                   140577
Ethnicity             123835
Voter Score           140577
Turnout Score         140577
Partisanship Score    140577
Kids in HH            134518
Liberal Ideology      134518
dtype: int64

In [5]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [6]:
df_voters.isnull()

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
140572,False,False,False,True,False,False,False,True,True
140573,False,False,False,True,False,False,False,True,True
140574,False,False,False,True,False,False,False,True,True
140575,False,False,False,True,False,False,False,True,True
140576,False,False,False,True,False,False,False,True,True

In [7]:
#drop any null or nan in the data frame 
df_voters.dropna(axis = 0, how = "any", thresh = None, subset = None, inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83.27,33.44,78.9,4.01,33.63
133405,Republican,M,65,Caucasian,12.59,98.67,18.3,19.08,9.96
133406,Republican,M,36,Caucasian,8.48,98.68,1.2,32.60,13.83
133407,Democrat,M,25,Uncoded,95.64,91.05,95.1,0.71,81.63
133408,Republican,F,36,Caucasian,14.54,88.19,67.6,24.69,26.05

In [8]:
df_voters.isnull().sum()

PartyName             0
Sex                   0
Age                   0
Ethnicity             0
Voter Score           0
Turnout Score         0
Partisanship Score    0
Kids in HH            0
Liberal Ideology      0
dtype: int64

In [9]:
df_voters.count()

PartyName             123486
Sex                   123486
Age                   123486
Ethnicity             123486
Voter Score           123486
Turnout Score         123486
Partisanship Score    123486
Kids in HH            123486
Liberal Ideology      123486
dtype: int64

In [10]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [11]:
# Convert Float64 to int dtypes
df_voters = df_voters.astype({'Voter Score':'int','Turnout Score':'int','Partisanship Score':'int','Kids in HH':'int','Liberal Ideology':'int'})
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33
133405,Republican,M,65,Caucasian,12,98,18,19,9
133406,Republican,M,36,Caucasian,8,98,1,32,13
133407,Democrat,M,25,Uncoded,95,91,95,0,81
133408,Republican,F,36,Caucasian,14,88,67,24,26

In [12]:
# Rename column 1

df_voters.rename(columns={'PartyName':'Party'}, inplace=True)
df_voters.head()

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1

In [13]:
# Create a list of our conditions
conditions = [
    (df_voters['Voter Score'] <= 34),
    (df_voters['Voter Score'] >= 35) & (df_voters['Voter Score'] <= 65),
    (df_voters['Voter Score'] >= 66) & (df_voters['Voter Score'] <=100)
    ]

# Create of values we want assigned to the conditions
values = ['False', 'True', 'False']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['Swing Voter'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,66,Hispanic,95,99,98,28,69,False
1,Republican,F,58,Caucasian,11,99,7,59,26,False
2,Republican,F,59,Caucasian,5,98,0,64,7,False
3,Republican,F,77,Caucasian,7,98,0,6,9,False
4,Republican,M,70,Caucasian,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33,False
133405,Republican,M,65,Caucasian,12,98,18,19,9,False
133406,Republican,M,36,Caucasian,8,98,1,32,13,False
133407,Democrat,M,25,Uncoded,95,91,95,0,81,False
133408,Republican,F,36,Caucasian,14,88,67,24,26,False

In [14]:
# Convert the target column values to low_chance and high_chance based on values

x = {'False':'Low_Chance'}
df_voters = df_voters.replace(x)

x = dict.fromkeys(['True'],'High_Chance')
df_voters = df_voters.replace(x)

df_voters.reset_index(inplace=True, drop=True)

df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,66,Hispanic,95,99,98,28,69,Low_Chance
1,Republican,F,58,Caucasian,11,99,7,59,26,Low_Chance
2,Republican,F,59,Caucasian,5,98,0,64,7,Low_Chance
3,Republican,F,77,Caucasian,7,98,0,6,9,Low_Chance
4,Republican,M,70,Caucasian,6,99,0,16,1,Low_Chance
...,...,...,...,...,...,...,...,...,...,...
123481,Other,F,29,Caucasian,83,33,78,4,33,Low_Chance
123482,Republican,M,65,Caucasian,12,98,18,19,9,Low_Chance
123483,Republican,M,36,Caucasian,8,98,1,32,13,Low_Chance
123484,Democrat,M,25,Uncoded,95,91,95,0,81,Low_Chance
123485,Republican,F,36,Caucasian,14,88,67,24,26,Low_Chance

In [15]:
# Converting label columns from text to numerical data as model only works with numerical data

X = pd.get_dummies(df_voters, columns=["Party","Sex","Ethnicity"]).drop("Swing Voter", axis=1)

# Create our target

y = df_voters["Swing Voter"]
X.head()

,Age,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,66,95,99,98,28,69,1,0,0,0,1,0,0,0,1,0,0
1,58,11,99,7,59,26,0,0,1,1,0,0,0,1,0,0,0
2,59,5,98,0,64,7,0,0,1,1,0,0,0,1,0,0,0
3,77,7,98,0,6,9,0,0,1,1,0,0,0,1,0,0,0
4,70,6,99,0,16,1,0,0,1,0,1,0,0,1,0,0,0

In [16]:
X.drop(columns=["Voter Score","Turnout Score","Partisanship Score","Kids in HH","Liberal Ideology"], inplace=True)
X.head()

,Age,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,66,1,0,0,0,1,0,0,0,1,0,0
1,58,0,0,1,1,0,0,0,1,0,0,0
2,59,0,0,1,1,0,0,0,1,0,0,0
3,77,0,0,1,1,0,0,0,1,0,0,0
4,70,0,0,1,0,1,0,0,1,0,0,0

In [17]:
# Convert Age into Labels? Also should I convert Low/High_Chance into binary code prior to drop?

In [18]:
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [20]:
# Determine the shape of our training and testing sets.
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(92614, 12)
(30872, 12)
(92614,)
(30872,)

In [21]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [22]:
# Creating the decision tree classifier instance.
model = tree.DecisionTreeClassifier()
# Fitting the model.
model = model.fit(X_train_scaled, y_train)

In [23]:
# Making predictions using the testing data.
predictions = model.predict(X_test_scaled)

In [24]:
predictions

array(['Low_Chance', 'Low_Chance', 'Low_Chance', ..., 'Low_Chance',
       'Low_Chance', 'Low_Chance'], dtype=object)

In [25]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0           53         3561
Actual 1          128        27130

In [26]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.8805066079295154

In [27]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           53         3561
Actual 1          128        27130

Accuracy Score : 0.8805066079295154
Classification Report
              precision    recall  f1-score   support

 High_Chance       0.29      0.01      0.03      3614
  Low_Chance       0.88      1.00      0.94     27258

    accuracy                           0.88     30872
   macro avg       0.59      0.50      0.48     30872
weighted avg       0.81      0.88      0.83     30872

# Random Forest Model

In [28]:
# Initial imports.
import pandas as pd
from path import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [29]:
#file path will be update to the table created in our sql database
file_path = "/Users/joshzaragoza/Arizona_Election_Project/Resources/Voter Data/Leg_District4.csv"
df_voters = pd.read_csv(file_path)
df_voters.head(10)

,PartyName,Sex,Age,Zip,LastName,FirstName,MiddleName,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,85018,Lozano,Javier,Mata,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,85254,Meell,Lana,Kay,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,85260,Collins,Anne,Melissa,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,85016,Bernhisel,Sandra,Jane,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,85018,Blanchard,Richard,Sheldon,Caucasian,6.78,99.31,0.7,16.74,1.73
5,Other,M,61,85018,Sexton,Kirk,Thomas,Caucasian,30.89,90.70,25.1,68.62,16.10
6,Other,F,58,85018,Sexton,Michelle,Lynn,Caucasian,54.23,92.16,30.0,82.50,25.78
7,Other,F,64,85018,Perry,Karen,Louise,Caucasian,15.13,99.34,1.2,42.51,6.80
8,Republican,M,79,85018,Skinner,Raymond,Alister,Caucasian,6.50,98.68,0.6,12.99,5.87
9,Other,M,44,85251,Dwyer,Jason,Paul,Caucasian,70.74,35.36,1.1,19.96,15.50

In [30]:
df_voters.drop(columns=["Zip","LastName","FirstName","MiddleName"], inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
140572,Republican,M,77,NaN,33.95,65.32,9.9,NaN,NaN
140573,Republican,F,57,NaN,18.43,67.75,4.3,NaN,NaN
140574,Republican,F,45,NaN,17.29,70.12,14.8,NaN,NaN
140575,Republican,M,60,NaN,13.54,67.16,4.3,NaN,NaN
140576,Republican,M,38,NaN,16.52,64.36,11.2,NaN,NaN

In [31]:
# Columns
df_voters.count()

PartyName             140577
Sex                   140577
Age                   140577
Ethnicity             123835
Voter Score           140577
Turnout Score         140577
Partisanship Score    140577
Kids in HH            134518
Liberal Ideology      134518
dtype: int64

In [32]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [33]:
df_voters.isnull()

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
140572,False,False,False,True,False,False,False,True,True
140573,False,False,False,True,False,False,False,True,True
140574,False,False,False,True,False,False,False,True,True
140575,False,False,False,True,False,False,False,True,True
140576,False,False,False,True,False,False,False,True,True

In [34]:
#drop any null or nan in the data frame 
df_voters.dropna(axis = 0, how = "any", thresh = None, subset = None, inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83.27,33.44,78.9,4.01,33.63
133405,Republican,M,65,Caucasian,12.59,98.67,18.3,19.08,9.96
133406,Republican,M,36,Caucasian,8.48,98.68,1.2,32.60,13.83
133407,Democrat,M,25,Uncoded,95.64,91.05,95.1,0.71,81.63
133408,Republican,F,36,Caucasian,14.54,88.19,67.6,24.69,26.05

In [35]:
df_voters.isnull().sum()

PartyName             0
Sex                   0
Age                   0
Ethnicity             0
Voter Score           0
Turnout Score         0
Partisanship Score    0
Kids in HH            0
Liberal Ideology      0
dtype: int64

In [36]:
df_voters.count()

PartyName             123486
Sex                   123486
Age                   123486
Ethnicity             123486
Voter Score           123486
Turnout Score         123486
Partisanship Score    123486
Kids in HH            123486
Liberal Ideology      123486
dtype: int64

In [37]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [38]:
# Convert Float64 to int dtypes
df_voters = df_voters.astype({'Voter Score':'int','Turnout Score':'int','Partisanship Score':'int','Kids in HH':'int','Liberal Ideology':'int'})
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33
133405,Republican,M,65,Caucasian,12,98,18,19,9
133406,Republican,M,36,Caucasian,8,98,1,32,13
133407,Democrat,M,25,Uncoded,95,91,95,0,81
133408,Republican,F,36,Caucasian,14,88,67,24,26

In [39]:
# Rename column 1

df_voters.rename(columns={'PartyName':'Party'}, inplace=True)
df_voters.head()

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1

In [40]:
# Create a list of our conditions
conditions = [
    (df_voters['Voter Score'] <= 34),
    (df_voters['Voter Score'] >= 35) & (df_voters['Voter Score'] <= 65),
    (df_voters['Voter Score'] >= 66) & (df_voters['Voter Score'] <=100)
    ]

# Create of values we want assigned to the conditions
values = ['False', 'True', 'False']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['Swing Voter'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,66,Hispanic,95,99,98,28,69,False
1,Republican,F,58,Caucasian,11,99,7,59,26,False
2,Republican,F,59,Caucasian,5,98,0,64,7,False
3,Republican,F,77,Caucasian,7,98,0,6,9,False
4,Republican,M,70,Caucasian,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33,False
133405,Republican,M,65,Caucasian,12,98,18,19,9,False
133406,Republican,M,36,Caucasian,8,98,1,32,13,False
133407,Democrat,M,25,Uncoded,95,91,95,0,81,False
133408,Republican,F,36,Caucasian,14,88,67,24,26,False

In [41]:
# Convert the target column values to low_chance and high_chance based on values

x = {'False':'Low_Chance'}
df_voters = df_voters.replace(x)

x = dict.fromkeys(['True'],'High_Chance')
df_voters = df_voters.replace(x)

df_voters.reset_index(inplace=True, drop=True)

df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,66,Hispanic,95,99,98,28,69,Low_Chance
1,Republican,F,58,Caucasian,11,99,7,59,26,Low_Chance
2,Republican,F,59,Caucasian,5,98,0,64,7,Low_Chance
3,Republican,F,77,Caucasian,7,98,0,6,9,Low_Chance
4,Republican,M,70,Caucasian,6,99,0,16,1,Low_Chance
...,...,...,...,...,...,...,...,...,...,...
123481,Other,F,29,Caucasian,83,33,78,4,33,Low_Chance
123482,Republican,M,65,Caucasian,12,98,18,19,9,Low_Chance
123483,Republican,M,36,Caucasian,8,98,1,32,13,Low_Chance
123484,Democrat,M,25,Uncoded,95,91,95,0,81,Low_Chance
123485,Republican,F,36,Caucasian,14,88,67,24,26,Low_Chance

In [42]:
# Create a list of our conditions
conditions = [
    (df_voters['Age'] >= 18) & (df_voters['Age'] <= 24),
    (df_voters['Age'] >= 25) & (df_voters['Age'] <= 34),
    (df_voters['Age'] >= 35) & (df_voters['Age'] <=44),
    (df_voters['Age'] >= 45) & (df_voters['Age'] <=54),
    (df_voters['Age'] >= 55) & (df_voters['Age'] <=64),
    (df_voters['Age'] >= 65),
    ]

# Create of values we want assigned to the conditions
values = ['1', '2', '3','4','5','6']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['Age'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,6,Hispanic,95,99,98,28,69,Low_Chance
1,Republican,F,5,Caucasian,11,99,7,59,26,Low_Chance
2,Republican,F,5,Caucasian,5,98,0,64,7,Low_Chance
3,Republican,F,6,Caucasian,7,98,0,6,9,Low_Chance
4,Republican,M,6,Caucasian,6,99,0,16,1,Low_Chance
...,...,...,...,...,...,...,...,...,...,...
123481,Other,F,2,Caucasian,83,33,78,4,33,Low_Chance
123482,Republican,M,6,Caucasian,12,98,18,19,9,Low_Chance
123483,Republican,M,3,Caucasian,8,98,1,32,13,Low_Chance
123484,Democrat,M,2,Uncoded,95,91,95,0,81,Low_Chance
123485,Republican,F,3,Caucasian,14,88,67,24,26,Low_Chance

In [43]:
# Converting label columns from text to numerical data as model only works with numerical data
X = pd.get_dummies(df_voters, columns=["Party","Sex","Ethnicity"])

In [44]:
X.head()

,Age,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,95,99,98,28,69,Low_Chance,1,0,0,0,1,0,0,0,1,0,0
1,5,11,99,7,59,26,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
2,5,5,98,0,64,7,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
3,6,7,98,0,6,9,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
4,6,6,99,0,16,1,Low_Chance,0,0,1,0,1,0,0,1,0,0,0

In [45]:
X.drop(columns=["Voter Score","Turnout Score","Partisanship Score","Kids in HH","Liberal Ideology"], inplace=True)
X.head()

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,Low_Chance,1,0,0,0,1,0,0,0,1,0,0
1,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
2,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
3,6,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
4,6,Low_Chance,0,0,1,0,1,0,0,1,0,0,0

In [46]:
# Saving cleaned data
file_path = "/Users/joshzaragoza/Arizona_Election_Project/LD_4_encoded.csv"
X.to_csv(file_path, index=False)

In [47]:
# Loading data
file_path = Path("/Users/joshzaragoza/Arizona_Election_Project/LD_4_encoded.csv")
df_voters = pd.read_csv(file_path)
df_voters.head()

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,Low_Chance,1,0,0,0,1,0,0,0,1,0,0
1,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
2,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
3,6,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
4,6,Low_Chance,0,0,1,0,1,0,0,1,0,0,0

In [48]:
# Define the features set.
X = df_voters.copy()
X = X.drop("Swing Voter", axis=1)
X.head()

,Age,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,1,0,0,0,1,0,0,0,1,0,0
1,5,0,0,1,1,0,0,0,1,0,0,0
2,5,0,0,1,1,0,0,0,1,0,0,0
3,6,0,0,1,1,0,0,0,1,0,0,0
4,6,0,0,1,0,1,0,0,1,0,0,0

In [49]:
# Create our target
y = df_voters["Swing Voter"].ravel()
y[:5]

array(['Low_Chance', 'Low_Chance', 'Low_Chance', 'Low_Chance',
       'Low_Chance'], dtype=object)

In [50]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [51]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [52]:
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=800, random_state=78)

In [53]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [54]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)
predictions

array(['Low_Chance', 'Low_Chance', 'Low_Chance', ..., 'Low_Chance',
       'Low_Chance', 'Low_Chance'], dtype=object)

In [55]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual Low_Chance", "Actual High_Chance"], columns=["Predicted Low_Chance", "Predicted High_Chance"])

cm_df

                    Predicted Low_Chance  Predicted High_Chance
Actual Low_Chance                      3                   3611
Actual High_Chance                     9                  27249

In [56]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.8827416429126717

In [57]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

                    Predicted Low_Chance  Predicted High_Chance
Actual Low_Chance                      3                   3611
Actual High_Chance                     9                  27249

Accuracy Score : 0.8827416429126717
Classification Report
              precision    recall  f1-score   support

 High_Chance       0.25      0.00      0.00      3614
  Low_Chance       0.88      1.00      0.94     27258

    accuracy                           0.88     30872
   macro avg       0.57      0.50      0.47     30872
weighted avg       0.81      0.88      0.83     30872

In [58]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.07717532, 0.12947784, 0.56885295, 0.20110591, 0.00361514,
       0.00361665, 0.00183251, 0.00149037, 0.00531607, 0.00301368,
       0.0016772 , 0.00282637])

In [59]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.5688529517197518, 'Party_Other'),
 (0.2011059051151517, 'Party_Republican'),
 (0.12947783841698654, 'Party_Democrat'),
 (0.07717532208653971, 'Age'),
 (0.005316067609089133, 'Ethnicity_Caucasian'),
 (0.0036166463879558595, 'Sex_M'),
 (0.003615143404983758, 'Sex_F'),
 (0.00301367616568326, 'Ethnicity_Hispanic'),
 (0.0028263669936414593, 'Ethnicity_Uncoded'),
 (0.001832505928702306, 'Ethnicity_African-American'),
 (0.0016772020874350857, 'Ethnicity_Native American'),
 (0.001490374084079495, 'Ethnicity_Asian')]

# Undersampling

In [60]:
# Loading data and importing dependicies
import pandas as pd
from path import Path
from collections import Counter

file_path = Path("/Users/joshzaragoza/Arizona_Election_Project/LD_4_encoded.csv")
df_voters = pd.read_csv(file_path)
df_voters.head()

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,Low_Chance,1,0,0,0,1,0,0,0,1,0,0
1,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
2,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
3,6,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
4,6,Low_Chance,0,0,1,0,1,0,0,1,0,0,0

In [61]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df_voters.copy()
df['Swing Voter'] = le.fit_transform(df['Swing Voter'])

In [62]:
df

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,1,1,0,0,0,1,0,0,0,1,0,0
1,5,1,0,0,1,1,0,0,0,1,0,0,0
2,5,1,0,0,1,1,0,0,0,1,0,0,0
3,6,1,0,0,1,1,0,0,0,1,0,0,0
4,6,1,0,0,1,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123481,2,1,0,1,0,1,0,0,0,1,0,0,0
123482,6,1,0,0,1,0,1,0,0,1,0,0,0
123483,3,1,0,0,1,0,1,0,0,1,0,0,0
123484,2,1,1,0,0,0,1,0,0,0,0,0,1
123485,3,1,0,0,1,1,0,0,0,1,0,0,0

In [63]:
x_cols = [i for i in df.columns if i not in ('Swing Voter')]
X = df[x_cols]
y = df['Swing Voter']

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [65]:
from imblearn.under_sampling import RandomUnderSampler
ros = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 10731, 1: 10731})

In [66]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [67]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 2751,   883],
       [ 5954, 21284]])

In [68]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.7692126938461245

In [69]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.32      0.76      0.78      0.45      0.77      0.59      3634
          1       0.96      0.78      0.76      0.86      0.77      0.59     27238

avg / total       0.88      0.78      0.76      0.81      0.77      0.59     30872

# SMOTEEN

In [70]:
# Loading data and importing dependicies
import pandas as pd
from path import Path
from collections import Counter

file_path = Path("/Users/joshzaragoza/Arizona_Election_Project/LD_4_encoded.csv")
df_voters = pd.read_csv(file_path)
df_voters.head()

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,Low_Chance,1,0,0,0,1,0,0,0,1,0,0
1,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
2,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
3,6,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
4,6,Low_Chance,0,0,1,0,1,0,0,1,0,0,0

In [71]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df_voters.copy()
df['Swing Voter'] = le.fit_transform(df['Swing Voter'])
df

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,1,1,0,0,0,1,0,0,0,1,0,0
1,5,1,0,0,1,1,0,0,0,1,0,0,0
2,5,1,0,0,1,1,0,0,0,1,0,0,0
3,6,1,0,0,1,1,0,0,0,1,0,0,0
4,6,1,0,0,1,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123481,2,1,0,1,0,1,0,0,0,1,0,0,0
123482,6,1,0,0,1,0,1,0,0,1,0,0,0
123483,3,1,0,0,1,0,1,0,0,1,0,0,0
123484,2,1,1,0,0,0,1,0,0,0,0,0,1
123485,3,1,0,0,1,1,0,0,0,1,0,0,0

In [72]:
x_cols = [i for i in df.columns if i not in ('Swing Voter')]
X = df[x_cols]
y = df['Swing Voter']

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [74]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X, y)

In [75]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [76]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[    3,  3631],
       [    2, 27236]])

In [77]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.5003760548843127

In [78]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.60      0.00      1.00      0.00      0.03      0.00      3634
          1       0.88      1.00      0.00      0.94      0.03      0.00     27238

avg / total       0.85      0.88      0.12      0.83      0.03      0.00     30872

In [79]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.07717532, 0.12947784, 0.56885295, 0.20110591, 0.00361514,
       0.00361665, 0.00183251, 0.00149037, 0.00531607, 0.00301368,
       0.0016772 , 0.00282637])

In [80]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.5688529517197518, 'Party_Other'),
 (0.2011059051151517, 'Party_Republican'),
 (0.12947783841698654, 'Party_Democrat'),
 (0.07717532208653971, 'Age'),
 (0.005316067609089133, 'Ethnicity_Caucasian'),
 (0.0036166463879558595, 'Sex_M'),
 (0.003615143404983758, 'Sex_F'),
 (0.00301367616568326, 'Ethnicity_Hispanic'),
 (0.0028263669936414593, 'Ethnicity_Uncoded'),
 (0.001832505928702306, 'Ethnicity_African-American'),
 (0.0016772020874350857, 'Ethnicity_Native American'),
 (0.001490374084079495, 'Ethnicity_Asian')]

In [81]:
# Loading data and importing dependicies
import pandas as pd
from path import Path
from collections import Counter

file_path = Path("/Users/joshzaragoza/Arizona_Election_Project/LD_4_encoded.csv")
df_voters = pd.read_csv(file_path)
df_voters.head()

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,Low_Chance,1,0,0,0,1,0,0,0,1,0,0
1,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
2,5,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
3,6,Low_Chance,0,0,1,1,0,0,0,1,0,0,0
4,6,Low_Chance,0,0,1,0,1,0,0,1,0,0,0

In [82]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df = df_voters.copy()
df['Swing Voter'] = le.fit_transform(df['Swing Voter'])
df

,Age,Swing Voter,Party_Democrat,Party_Other,Party_Republican,Sex_F,Sex_M,Ethnicity_African-American,Ethnicity_Asian,Ethnicity_Caucasian,Ethnicity_Hispanic,Ethnicity_Native American,Ethnicity_Uncoded
0,6,1,1,0,0,0,1,0,0,0,1,0,0
1,5,1,0,0,1,1,0,0,0,1,0,0,0
2,5,1,0,0,1,1,0,0,0,1,0,0,0
3,6,1,0,0,1,1,0,0,0,1,0,0,0
4,6,1,0,0,1,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
123481,2,1,0,1,0,1,0,0,0,1,0,0,0
123482,6,1,0,0,1,0,1,0,0,1,0,0,0
123483,3,1,0,0,1,0,1,0,0,1,0,0,0
123484,2,1,1,0,0,0,1,0,0,0,0,0,1
123485,3,1,0,0,1,1,0,0,0,1,0,0,0

In [83]:
x_cols = [i for i in df.columns if i not in ('Swing Voter')]
X = df[x_cols]
y = df['Swing Voter']

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [85]:
from imblearn.under_sampling import RandomUnderSampler
ros = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 10731, 1: 10731})

In [86]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [87]:
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 2751,   883],
       [ 5954, 21284]])

In [88]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.7692126938461245

In [89]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.32      0.76      0.78      0.45      0.77      0.59      3634
          1       0.96      0.78      0.76      0.86      0.77      0.59     27238

avg / total       0.88      0.78      0.76      0.81      0.77      0.59     30872

In [ ]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)