In [1]:
# Import our dependencies
import pandas as pd
import matplotlib as plt
import sklearn as skl
import tensorflow as tf
from path import Path
import numpy as np

In [2]:
#file path will be update to the table created in our sql database
file_path = "/Users/joshzaragoza/Arizona_Election_Project/Resources/Voter Data/Leg_District4.csv"
df_voters = pd.read_csv(file_path)
df_voters.head(10)

,PartyName,Sex,Age,Zip,LastName,FirstName,MiddleName,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,85018,Lozano,Javier,Mata,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,85254,Meell,Lana,Kay,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,85260,Collins,Anne,Melissa,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,85016,Bernhisel,Sandra,Jane,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,85018,Blanchard,Richard,Sheldon,Caucasian,6.78,99.31,0.7,16.74,1.73
5,Other,M,61,85018,Sexton,Kirk,Thomas,Caucasian,30.89,90.70,25.1,68.62,16.10
6,Other,F,58,85018,Sexton,Michelle,Lynn,Caucasian,54.23,92.16,30.0,82.50,25.78
7,Other,F,64,85018,Perry,Karen,Louise,Caucasian,15.13,99.34,1.2,42.51,6.80
8,Republican,M,79,85018,Skinner,Raymond,Alister,Caucasian,6.50,98.68,0.6,12.99,5.87
9,Other,M,44,85251,Dwyer,Jason,Paul,Caucasian,70.74,35.36,1.1,19.96,15.50

In [3]:
df_voters.drop(columns=["Zip","LastName","FirstName","MiddleName"], inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
140572,Republican,M,77,NaN,33.95,65.32,9.9,NaN,NaN
140573,Republican,F,57,NaN,18.43,67.75,4.3,NaN,NaN
140574,Republican,F,45,NaN,17.29,70.12,14.8,NaN,NaN
140575,Republican,M,60,NaN,13.54,67.16,4.3,NaN,NaN
140576,Republican,M,38,NaN,16.52,64.36,11.2,NaN,NaN

In [4]:
# Columns
df_voters.count()

PartyName             140577
Sex                   140577
Age                   140577
Ethnicity             123835
Voter Score           140577
Turnout Score         140577
Partisanship Score    140577
Kids in HH            134518
Liberal Ideology      134518
dtype: int64

In [5]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [6]:
df_voters.isnull()

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
140572,False,False,False,True,False,False,False,True,True
140573,False,False,False,True,False,False,False,True,True
140574,False,False,False,True,False,False,False,True,True
140575,False,False,False,True,False,False,False,True,True
140576,False,False,False,True,False,False,False,True,True

In [7]:
#drop any null or nan in the data frame 
df_voters.dropna(axis = 0, how = "any", thresh = None, subset = None, inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83.27,33.44,78.9,4.01,33.63
133405,Republican,M,65,Caucasian,12.59,98.67,18.3,19.08,9.96
133406,Republican,M,36,Caucasian,8.48,98.68,1.2,32.60,13.83
133407,Democrat,M,25,Uncoded,95.64,91.05,95.1,0.71,81.63
133408,Republican,F,36,Caucasian,14.54,88.19,67.6,24.69,26.05

In [8]:
df_voters.isnull().sum()

PartyName             0
Sex                   0
Age                   0
Ethnicity             0
Voter Score           0
Turnout Score         0
Partisanship Score    0
Kids in HH            0
Liberal Ideology      0
dtype: int64

In [9]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [10]:
# Convert Float64 to int dtypes
df_voters = df_voters.astype({'Voter Score':'int','Turnout Score':'int','Partisanship Score':'int','Kids in HH':'int','Liberal Ideology':'int'})
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33
133405,Republican,M,65,Caucasian,12,98,18,19,9
133406,Republican,M,36,Caucasian,8,98,1,32,13
133407,Democrat,M,25,Uncoded,95,91,95,0,81
133408,Republican,F,36,Caucasian,14,88,67,24,26

In [11]:
# Rename column 1
df_voters.rename(columns={'PartyName':'Party'}, inplace=True)
df_voters.head()

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1

In [12]:
# Create a list of our conditions
conditions = [
    (df_voters['Voter Score'] <= 34),
    (df_voters['Voter Score'] >= 35) & (df_voters['Voter Score'] <= 65),
    (df_voters['Voter Score'] >= 66) & (df_voters['Voter Score'] <=100)
    ]

# Create of values we want assigned to the conditions
values = ['False', 'True', 'False']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['Swing Voter'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,66,Hispanic,95,99,98,28,69,False
1,Republican,F,58,Caucasian,11,99,7,59,26,False
2,Republican,F,59,Caucasian,5,98,0,64,7,False
3,Republican,F,77,Caucasian,7,98,0,6,9,False
4,Republican,M,70,Caucasian,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33,False
133405,Republican,M,65,Caucasian,12,98,18,19,9,False
133406,Republican,M,36,Caucasian,8,98,1,32,13,False
133407,Democrat,M,25,Uncoded,95,91,95,0,81,False
133408,Republican,F,36,Caucasian,14,88,67,24,26,False

In [13]:
# Create a list of our conditions
conditions = [
    (df_voters['Age'] >= 18) & (df_voters['Age'] <= 24),
    (df_voters['Age'] >= 25) & (df_voters['Age'] <= 34),
    (df_voters['Age'] >= 35) & (df_voters['Age'] <=44),
    (df_voters['Age'] >= 45) & (df_voters['Age'] <=54),
    (df_voters['Age'] >= 55) & (df_voters['Age'] <=64),
    (df_voters['Age'] >= 65),
    ]

# Create of values we want assigned to the conditions
values = ['1', '2', '3','4','5','6']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['Age'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,Democrat,M,6,Hispanic,95,99,98,28,69,False
1,Republican,F,5,Caucasian,11,99,7,59,26,False
2,Republican,F,5,Caucasian,5,98,0,64,7,False
3,Republican,F,6,Caucasian,7,98,0,6,9,False
4,Republican,M,6,Caucasian,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,Other,F,2,Caucasian,83,33,78,4,33,False
133405,Republican,M,6,Caucasian,12,98,18,19,9,False
133406,Republican,M,3,Caucasian,8,98,1,32,13,False
133407,Democrat,M,2,Uncoded,95,91,95,0,81,False
133408,Republican,F,3,Caucasian,14,88,67,24,26,False

In [14]:
# Changing to numerical by label encoder
from sklearn.preprocessing import LabelEncoder 
number = LabelEncoder()
df_voters["Party"] = number.fit_transform(df_voters["Party"])
df_voters["Sex"] = number.fit_transform(df_voters["Sex"])
df_voters["Ethnicity"] = number.fit_transform(df_voters["Ethnicity"])
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,Swing Voter
0,0,1,6,3,95,99,98,28,69,False
1,2,0,5,2,11,99,7,59,26,False
2,2,0,5,2,5,98,0,64,7,False
3,2,0,6,2,7,98,0,6,9,False
4,2,1,6,2,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,1,0,2,2,83,33,78,4,33,False
133405,2,1,6,2,12,98,18,19,9,False
133406,2,1,3,2,8,98,1,32,13,False
133407,0,1,2,5,95,91,95,0,81,False
133408,2,0,3,2,14,88,67,24,26,False

In [15]:
#Drop columns that doesn't impact Swing Voter chances
df_voters.drop(columns=["Voter Score","Turnout Score","Partisanship Score","Kids in HH", "Liberal Ideology"], inplace=True)
df_voters

        Party  Sex Age  Ethnicity Swing Voter
0           0    1   6          3       False
1           2    0   5          2       False
2           2    0   5          2       False
3           2    0   6          2       False
4           2    1   6          2       False
...       ...  ...  ..        ...         ...
133404      1    0   2          2       False
133405      2    1   6          2       False
133406      2    1   3          2       False
133407      0    1   2          5       False
133408      2    0   3          2       False

[123486 rows x 5 columns]

# Support Vectors Machine

In [16]:
y = df_voters["Swing Voter"]
X = df_voters.drop(columns="Swing Voter")

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  random_state=1, stratify=y)
X_train.shape

(92614, 4)

In [18]:
from sklearn.svm import SVC
model = SVC(kernel='linear')

In [19]:
model.fit(X_train, y_train)

SVC(kernel='linear')

In [20]:
y_pred = model.predict(X_test)
results = pd.DataFrame({
   "Prediction": y_pred,
   "Actual": y_test
}).reset_index(drop=True)
results.head()

  Prediction Actual
0      False  False
1      False  False
2      False  False
3      False  False
4      False  False

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8836810054418243

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

       False       0.88      1.00      0.94     27281
        True       0.00      0.00      0.00      3591

    accuracy                           0.88     30872
   macro avg       0.44      0.50      0.47     30872
weighted avg       0.78      0.88      0.83     30872

/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# Logistic Regression

In [23]:
#file path will be update to the table created in our sql database
file_path = "/Users/joshzaragoza/Arizona_Election_Project/Resources/Voter Data/Leg_District4.csv"
df_voters = pd.read_csv(file_path)
df_voters.head(10)

,PartyName,Sex,Age,Zip,LastName,FirstName,MiddleName,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,85018,Lozano,Javier,Mata,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,85254,Meell,Lana,Kay,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,85260,Collins,Anne,Melissa,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,85016,Bernhisel,Sandra,Jane,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,85018,Blanchard,Richard,Sheldon,Caucasian,6.78,99.31,0.7,16.74,1.73
5,Other,M,61,85018,Sexton,Kirk,Thomas,Caucasian,30.89,90.70,25.1,68.62,16.10
6,Other,F,58,85018,Sexton,Michelle,Lynn,Caucasian,54.23,92.16,30.0,82.50,25.78
7,Other,F,64,85018,Perry,Karen,Louise,Caucasian,15.13,99.34,1.2,42.51,6.80
8,Republican,M,79,85018,Skinner,Raymond,Alister,Caucasian,6.50,98.68,0.6,12.99,5.87
9,Other,M,44,85251,Dwyer,Jason,Paul,Caucasian,70.74,35.36,1.1,19.96,15.50

In [24]:
df_voters.drop(columns=["Zip","LastName","FirstName","MiddleName"], inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
140572,Republican,M,77,NaN,33.95,65.32,9.9,NaN,NaN
140573,Republican,F,57,NaN,18.43,67.75,4.3,NaN,NaN
140574,Republican,F,45,NaN,17.29,70.12,14.8,NaN,NaN
140575,Republican,M,60,NaN,13.54,67.16,4.3,NaN,NaN
140576,Republican,M,38,NaN,16.52,64.36,11.2,NaN,NaN

In [25]:
# Columns
df_voters.count()

PartyName             140577
Sex                   140577
Age                   140577
Ethnicity             123835
Voter Score           140577
Turnout Score         140577
Partisanship Score    140577
Kids in HH            134518
Liberal Ideology      134518
dtype: int64

In [26]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [27]:
df_voters.isnull()

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
140572,False,False,False,True,False,False,False,True,True
140573,False,False,False,True,False,False,False,True,True
140574,False,False,False,True,False,False,False,True,True
140575,False,False,False,True,False,False,False,True,True
140576,False,False,False,True,False,False,False,True,True

In [28]:
#drop any null or nan in the data frame 
df_voters.dropna(axis = 0, how = "any", thresh = None, subset = None, inplace=True)
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95.82,99.33,98.9,28.32,69.16
1,Republican,F,58,Caucasian,11.86,99.23,7.1,59.40,26.26
2,Republican,F,59,Caucasian,5.34,98.70,0.6,64.63,7.89
3,Republican,F,77,Caucasian,7.09,98.82,0.9,6.98,9.02
4,Republican,M,70,Caucasian,6.78,99.31,0.7,16.74,1.73
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83.27,33.44,78.9,4.01,33.63
133405,Republican,M,65,Caucasian,12.59,98.67,18.3,19.08,9.96
133406,Republican,M,36,Caucasian,8.48,98.68,1.2,32.60,13.83
133407,Democrat,M,25,Uncoded,95.64,91.05,95.1,0.71,81.63
133408,Republican,F,36,Caucasian,14.54,88.19,67.6,24.69,26.05

In [29]:
df_voters.isnull().sum()

PartyName             0
Sex                   0
Age                   0
Ethnicity             0
Voter Score           0
Turnout Score         0
Partisanship Score    0
Kids in HH            0
Liberal Ideology      0
dtype: int64

In [30]:
df_voters.dtypes

PartyName              object
Sex                    object
Age                     int64
Ethnicity              object
Voter Score           float64
Turnout Score         float64
Partisanship Score    float64
Kids in HH            float64
Liberal Ideology      float64
dtype: object

In [31]:
# Convert Float64 to int dtypes
df_voters = df_voters.astype({'Voter Score':'int','Turnout Score':'int','Partisanship Score':'int','Kids in HH':'int','Liberal Ideology':'int'})
df_voters

,PartyName,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1
...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33
133405,Republican,M,65,Caucasian,12,98,18,19,9
133406,Republican,M,36,Caucasian,8,98,1,32,13
133407,Democrat,M,25,Uncoded,95,91,95,0,81
133408,Republican,F,36,Caucasian,14,88,67,24,26

In [32]:
# Rename column 1
df_voters.rename(columns={'PartyName':'Party'}, inplace=True)
df_voters.head()

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology
0,Democrat,M,66,Hispanic,95,99,98,28,69
1,Republican,F,58,Caucasian,11,99,7,59,26
2,Republican,F,59,Caucasian,5,98,0,64,7
3,Republican,F,77,Caucasian,7,98,0,6,9
4,Republican,M,70,Caucasian,6,99,0,16,1

In [33]:
# Create a list of our conditions
conditions = [
    (df_voters['Voter Score'] <= 34),
    (df_voters['Voter Score'] >= 35) & (df_voters['Voter Score'] <= 65),
    (df_voters['Voter Score'] >= 66) & (df_voters['Voter Score'] <=100)
    ]

# Create of values we want assigned to the conditions
values = ['False', 'True', 'False']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['SwingVoter'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,SwingVoter
0,Democrat,M,66,Hispanic,95,99,98,28,69,False
1,Republican,F,58,Caucasian,11,99,7,59,26,False
2,Republican,F,59,Caucasian,5,98,0,64,7,False
3,Republican,F,77,Caucasian,7,98,0,6,9,False
4,Republican,M,70,Caucasian,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,Other,F,29,Caucasian,83,33,78,4,33,False
133405,Republican,M,65,Caucasian,12,98,18,19,9,False
133406,Republican,M,36,Caucasian,8,98,1,32,13,False
133407,Democrat,M,25,Uncoded,95,91,95,0,81,False
133408,Republican,F,36,Caucasian,14,88,67,24,26,False

In [34]:
# Create a list of our conditions
conditions = [
    (df_voters['Age'] >= 18) & (df_voters['Age'] <= 24),
    (df_voters['Age'] >= 25) & (df_voters['Age'] <= 34),
    (df_voters['Age'] >= 35) & (df_voters['Age'] <=44),
    (df_voters['Age'] >= 45) & (df_voters['Age'] <=54),
    (df_voters['Age'] >= 55) & (df_voters['Age'] <=64),
    (df_voters['Age'] >= 65),
    ]

# Create of values we want assigned to the conditions
values = ['1', '2', '3','4','5','6']

# Create a new column with np.select to assign values to it using our lists as arguments
df_voters['Age'] = np.select(conditions, values)

# Display updated DataFrame
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,SwingVoter
0,Democrat,M,6,Hispanic,95,99,98,28,69,False
1,Republican,F,5,Caucasian,11,99,7,59,26,False
2,Republican,F,5,Caucasian,5,98,0,64,7,False
3,Republican,F,6,Caucasian,7,98,0,6,9,False
4,Republican,M,6,Caucasian,6,99,0,16,1,False
...,...,...,...,...,...,...,...,...,...,...
133404,Other,F,2,Caucasian,83,33,78,4,33,False
133405,Republican,M,6,Caucasian,12,98,18,19,9,False
133406,Republican,M,3,Caucasian,8,98,1,32,13,False
133407,Democrat,M,2,Uncoded,95,91,95,0,81,False
133408,Republican,F,3,Caucasian,14,88,67,24,26,False

In [35]:
# Changing to numerical by label encoder
from sklearn.preprocessing import LabelEncoder 
number = LabelEncoder()
df_voters["Party"] = number.fit_transform(df_voters["Party"])
df_voters["Sex"] = number.fit_transform(df_voters["Sex"])
df_voters["Ethnicity"] = number.fit_transform(df_voters["Ethnicity"])
df_voters["SwingVoter"] = number.fit_transform(df_voters["SwingVoter"])
df_voters

,Party,Sex,Age,Ethnicity,Voter Score,Turnout Score,Partisanship Score,Kids in HH,Liberal Ideology,SwingVoter
0,0,1,6,3,95,99,98,28,69,0
1,2,0,5,2,11,99,7,59,26,0
2,2,0,5,2,5,98,0,64,7,0
3,2,0,6,2,7,98,0,6,9,0
4,2,1,6,2,6,99,0,16,1,0
...,...,...,...,...,...,...,...,...,...,...
133404,1,0,2,2,83,33,78,4,33,0
133405,2,1,6,2,12,98,18,19,9,0
133406,2,1,3,2,8,98,1,32,13,0
133407,0,1,2,5,95,91,95,0,81,0
133408,2,0,3,2,14,88,67,24,26,0

In [36]:
#Drop columns that doesn't impact Swing Voter chances
df_voters.drop(columns=["Voter Score","Turnout Score","Partisanship Score","Kids in HH", "Liberal Ideology"], inplace=True)
df_voters

        Party  Sex Age  Ethnicity  SwingVoter
0           0    1   6          3           0
1           2    0   5          2           0
2           2    0   5          2           0
3           2    0   6          2           0
4           2    1   6          2           0
...       ...  ...  ..        ...         ...
133404      1    0   2          2           0
133405      2    1   6          2           0
133406      2    1   3          2           0
133407      0    1   2          5           0
133408      2    0   3          2           0

[123486 rows x 5 columns]

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
y = df_voters["SwingVoter"]
X = df_voters.drop(columns="SwingVoter")

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y, random_state=1, stratify=y)

In [40]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
   max_iter=200, random_state=1)

In [41]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [42]:
y_pred = classifier.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8836810054418243

In [44]:
df = pd.DataFrame({
    'Actual': y_test,
    'Predicted': list(y_pred)
})

In [45]:
df

        Actual  Predicted
10338        0          0
121808       0          0
13337        0          0
3773         0          0
101486       0          0
...        ...        ...
105916       0          0
45209        0          0
119382       0          0
37319        0          0
82416        0          0

[30872 rows x 2 columns]

In [46]:
df.Actual.value_counts()

0    27281
1     3591
Name: Actual, dtype: int64

In [47]:
df.Predicted.value_counts()

0    30872
Name: Predicted, dtype: int64

In [48]:
from sklearn.metrics import classification_report

In [49]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     27281
           1       0.00      0.00      0.00      3591

    accuracy                           0.88     30872
   macro avg       0.44      0.50      0.47     30872
weighted avg       0.78      0.88      0.83     30872

/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

# Undersampling Majority 0 to Minority 1

In [50]:
df = df_voters.copy()

In [51]:
df.sample()

        Party  Sex Age  Ethnicity  SwingVoter
102825      0    0   2          2           0

In [52]:
df_zeros = df[df.SwingVoter == 0]
df_ones = df[df.SwingVoter == 1]

In [53]:
df_zeros.shape

(109121, 5)

In [54]:
df_zeros = df_zeros.sample(df_ones.shape[0])

In [55]:
df_zeros.shape

(14365, 5)

In [56]:
df_ones.shape

(14365, 5)

In [57]:
undersample_df = pd.concat([df_zeros, df_ones])

In [58]:
undersample_df.shape

(28730, 5)

In [59]:
undersample_df.head(3)

       Party  Sex Age  Ethnicity  SwingVoter
97348      1    1   3          2           0
15752      2    0   5          2           0
33086      0    0   5          2           0

In [60]:
X = undersample_df.drop(['SwingVoter'], axis=1)

In [61]:
y = undersample_df['SwingVoter']

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [63]:
model = LogisticRegression()

In [64]:
model.fit(X_train, y_train)

LogisticRegression()

In [65]:
y_pred = model.predict(X_test)

In [66]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.58      0.62      0.60      2846
           1       0.60      0.56      0.58      2900

    accuracy                           0.59      5746
   macro avg       0.59      0.59      0.59      5746
weighted avg       0.59      0.59      0.59      5746